Repository henriqueburgos/diario-viagens1, pull requests merged in 2022-06, with the labels that each got.

#20 Implementacao update perfil
  src/app/app.module.ts
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/components/user/user.component.html
  src/app/auth/components/user/user.component.scss
  src/app/auth/components/user/user.component.spec.ts
  src/app/auth/components/user/user.component.ts
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.scss
  src/app/core/components/navbar/navbar.component.ts
  src/app/core/models/diario.ts
  src/app/core/models/infoUser.ts
  src/app/core/services/auth/auth.service.ts
  src/app/core/services/diarios/diarios.service.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/diarios/components/diario-detail/diario-detail.component.html
  src/app/diarios/components/diario-detail/diario-detail.component.scss
  src/app/diarios/components/diario-detail/diario-detail.component.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/diario-list/diario-list.component.ts
Labels: enhancement

#23 Implementado funcionalidade de super-admin
  src/app/app.module.ts
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/components/user-admin/user-admin.component.html
  src/app/auth/components/user-admin/user-admin.component.scss
  src/app/auth/components/user-admin/user-admin.component.spec.ts
  src/app/auth/components/user-admin/user-admin.component.ts
  src/app/auth/components/user/user.component.html
  src/app/auth/components/user/user.component.scss
  src/app/auth/components/user/user.component.ts
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.scss
  src/app/core/components/navbar/navbar.component.ts
  src/app/core/models/infoUser.ts
  src/app/core/services/user/user.service.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/diario-list/diario-list.component.ts
Labels: enhancement

#29 Adição dos termos de privacidade
  src/app/app.module.ts
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.ts
  src/app/auth/components/login-providers/login-providers/login-providers.component.html
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
  src/app/shared/components/termos-de-privacidade/termos-de-privacidade.component.html
  src/app/shared/components/termos-de-privacidade/termos-de-privacidade.component.scss
  src/app/shared/components/termos-de-privacidade/termos-de-privacidade.component.spec.ts
  src/app/shared/components/termos-de-privacidade/termos-de-privacidade.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#32 Atualização Visual login/cadastro e Clean Code.
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.scss
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
  src/app/core/components/navbar/navbar.component.html
  src/styles.scss
Labels: code update

#34 Landing page: Criar uma página principal.
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/auth/components/user-admin/user-admin.component.scss
  src/app/auth/components/user/user.component.scss
  src/app/core/components/footer/footer.component.html
  src/app/core/components/footer/footer.component.scss
  src/app/core/components/footer/footer.component.spec.ts
  src/app/core/components/footer/footer.component.ts
  src/app/core/components/navbar/navbar.component.html
  src/app/core/components/navbar/navbar.component.scss
  src/app/core/core.module.ts
  src/app/home/home.component.html
  src/app/home/home.component.scss
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/home/styles/cards.scss
  src/app/home/styles/keyframes.scss
  src/app/home/styles/media-queries.scss
  src/assets/img/bg-home-desktop-1000.png
  src/assets/img/bg-home-desktop-720.png
  src/assets/img/bg-home-desktop-860.png
  src/assets/img/bg-home-desktop.png
  src/index.html
  src/styles.scss
Labels: enhancement, code update

#36 Implementação de GridList na page de listagem de diarios.
  src/app/core/services/diarios/diarios.service.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/diario-list/diario-list.component.ts
Labels: enhancement

#37 Recaptcha extra addition
  src/app/auth/auth.module.ts
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.scss
  src/app/auth/components/cadastro/cadastro.component.ts
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.ts
  src/app/shared/components/recaptcha/recaptcha.component.html
  src/app/shared/components/recaptcha/recaptcha.component.scss
  src/app/shared/components/recaptcha/recaptcha.component.spec.ts
  src/app/shared/components/recaptcha/recaptcha.component.ts
  src/app/shared/shared.module.ts
  src/styles.scss
Labels: enhancement, code update

#39 Criacao da funcionalidade de bate-papo
  src/app/chat-global/chat-global.component.html
  src/app/chat-global/chat-global.component.scss
  src/app/chat-global/chat-global.component.spec.ts
  src/app/chat-global/chat-global.component.ts
  src/app/core/models/Mensagem.ts
  src/app/core/services/auth/auth.service.ts
  src/app/core/services/chat/chat.service.spec.ts
  src/app/core/services/chat/chat.service.ts
  src/app/core/services/diarios/diarios.service.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/diario-list/diario-list.component.ts
  src/app/diarios/diarios.module.ts
Labels: enhancement

#43 Estilizacão da página de login
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.scss
  src/app/auth/components/login/login.component.ts
  src/app/auth/components/login/styles/keyframes.scss
  src/app/auth/components/login/styles/media-queries.scss
  src/assets/img/logo.png
  src/index.html
  src/styles.scss
Labels: code update

#46 Adição de updateData na interface diario
  src/app/core/models/diario.ts
  src/app/core/services/diarios/diarios.service.ts
  src/app/diarios/components/diario-list/diario-list.component.html
Labels: enhancement, code update

#47 Implementação de Like na pagina de diario por uid.
  src/app/core/models/diario.ts
  src/app/core/services/diarios/diarios.service.ts
  src/app/diarios/components/diario-detail/diario-detail.component.html
  src/app/diarios/components/diario-detail/diario-detail.component.scss
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/diario-list/diario-list.component.ts
Labels: enhancement

#48 Implementação de Paginação
  package-lock.json
  package.json
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.ts
  src/app/diarios/diarios.module.ts
Labels: documentation, enhancement
